syntax match todoTodo /^\s*TODO.*/
syntax match todoDone /^\s*DONE.*/
syntax match todoHold /^\s*HOLD.*/
syntax match todoIdea /^\s*IDEA.*/
syntax match todoItem /^\s*ITEM.*/
syntax match todoList /^\s*LIST.*/
syntax match todoNote /^\s*NOTE.*/
syntax match todoOpen /^\s*OPEN.*/
syntax match todoPunt /^\s*PUNT.*/
syntax match todoTask /^\s*TASK.*/
